hub/urls.py
# hub/urls.py

from django.conf.urls import url
from . import views


urlpatterns = [ 
    url(r'^$', views.list, name='hub_list'),
    url(r'^mynovel/$', views.mynovel, name='my_novel'),
    url(r'^sharednovel/$', views.sharednovel, name='shared_novel'),
    url(r'^mynovel/(?P<id>\d+)/$', views.post_detail, name='post_detail'),		
    url(r'^mynovel/new/$', views.post_new, name='post_new'),		
    url(r'^mynovel/(?P<id>\d+)/edit/$', views.post_edit, name = 'post_edit'),
    
]   

morakmorak/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.shortcuts import redirect


def root(request):
    return redirect('firstpage.html')


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')), #장고 기본 auth앱과 연동해서 사용하므로, namespace 적용하지 않음! 
    url(r'^accounts/', include('allauth.urls')), #include를 사용할 시에는 url에 $를 표시하면 안됨. $ 표시할 경우 패턴매칭 끝남.
    url(r'^hub/', include('hub.urls', namespace='hub')),
    url(r'^practice/', include('practice.urls', namespace='practice')),
   
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
   ]
#runserver 실행했을때, debug toolbar 활성화

practice/urls.py
# practice/urls.py

from django.conf.urls import url
from . import views


urlpatterns = [ 
    url(r'^$', views.contents_list, name="contents_list"),
    url(r'^relaynovel/$', views.relaynovel, name="relay_novel"),
    url(r'^radiostation/$', views.radiostation, name="radio_station"),
    url(r'^relaynovel/(?P<id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^relaynovel/new/$', views.post_new, name='post_new'),
    url(r'^relaynovel/(?P<id>\d+)/edit/$', views.post_edit, name = 'post_edit'),
]   

hub/models.py
# hub/models.py
import re
from django import forms
from django.forms import ValidationError
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models

# Create your models here.

class MyNovel(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.CharField(max_length=100, blank=True)
    STATUS_CHOICES = (
        ('d', '작성중'),
        ('f', '작성완료'),
        ('p', '출판'),
    )
    
    status = models.Charfield(max_length=1, choices=STATUS_CHOICES)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('hub:post_detail', args=[self.id])



class Comment(models.Model):
    post = models.ForeignKey(MyNovel)
    author = models.Charfield(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    

practice/models.py
# practice/models.py
from django.db import models
from django.shortcuts import reverse


class StartRelayNovel(models.Model):
    title = models.CharField(max_length=100, verbose_name='소설 제목') #릴레이 소설 제목
    content = models.TextField(help_text='새로운 릴레이 소설의 문을 열어보세요!') #첫번째로 작성된 소설
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


   # def save(self, commit=True):
    #    post = StartRelayNovel(**self.cleaned_data)
     #   if commit:
      #      post.save()
       #     return post

    def get_absolute_url(self):
        return reverse('practice:post_detail', args=[self.id])

    
class RelayNovelSequel(models.Model):
    StartRelayNovel = models.ForeignKey(StartRelayNovel)
    summary = models.TextField(help_text='이어지는 내용을 짧게 요약해 주세요!')
    content = models.TextField(help_text='재치있게 소설을 이어나가 보세요!')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class RadioStation(models.Model):
    writer = models.CharField(max_length=20, verbose_name='보내는 이')
    content = models.TextField(help_text='모모언니에게 사연을 보내보세요!')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class MomoReply(models.Model):
    RadioStation = models.ForeignKey(RadioStation)
    content = models.TextField(help_text='모모언니가 되어 사연에 답장해보세요!')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

practice/forms.py
from django import forms
from .models import StartRelayNovel

class PostForm(forms.ModelForm):
    # dummy = forms.CharField(widget=NaverMapPointWidget(attrs={'width':"100%", 'height':200}))

    class Meta:
        model = StartRelayNovel
        fields = '__all__'

practice/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import StartRelayNovel,RadioStation
from .forms import PostForm
from django.contrib import messages
from django.http import Http404


# Create your views here.


def contents_list(request):  
    response = render(request, 'practice/contents_list.html')
    return response


def relaynovel(request):
    relaynovel = StartRelayNovel.objects.all()
    return render(request, 'practice/relaynovel_list.html', {
        'relaynovel_list': relaynovel,
        })


def radiostation(request):
    radiostation = RadioStation.objects.all()
    return render(request, 'practice/radiostation.html', {
        'radiostation_list': radiostation,
        })


def post_detail(request, id):
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404

    post = get_object_or_404(StartRelayNovel,id=id)
    return render(request, 'practice/post_detail.html',{
            'post':post,
        })

def post_edit(request, id):
    post = get_object_or_404(StartRelayNovel, id=id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post) 
        if form.is_valid():
            post = form.save()
            messages.success(request, '포스팅을 수정하였습니다.')
            return redirect(post) #post.get_absolute_url() => post detail
    else:
        form = PostForm(instance=post)
    return render(request, 'practice/post_form.html', {
            'form':form,
        })


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, '새 포스팅을 저장하였습니다.')
            return redirect(post) #post.get_absolute_url() => post detail
    else:
        form = PostForm()
    return render(request, 'practice/post_form.html', {
            'form':form,
        })

practice/templates/practice/contents_list.html
{% extends "practice/layout.html" %}

{% block content %}

<!--
<form action="" method="get">
    <input type="text" name="q" value="{{ q }}" />
    <input type="submit" value="검색" class="btn btn-primary" />
</form>   
-->

<div class ="row">
    <div class="col-sm-12">
        <div class="alert alert-info">         
            <ul>
            <li>모락모락 글쓰기 연습장 컨텐츠 리스트 입니다.</li>
            <li>다양한 글쓰기 방식으로 실력을 상승시켜보세요.</li>
            <li> <a href ="{%url "practice:relay_novel" %}" >릴레이 소설 쓰기</a> </li>
            <li> <a href ="{%url "practice:radio_station" %}" >모모언니에게 보내는 라디오사연</a> </li>
            <li> <a href ="#" >사진 보고 서술하기</a> </li>
            <li> <a href ="#" >변명집 작성하기</a> </li>
            <li> <a href ="#" >VS 소설 쓰기</a> </li>
            </ul>
        </div>

{% endblock %}

practice/templates/practice/layout.html
{% extends "layout.html" %}

{% block title %}모락모락 단편소설 글쓰기 허브{% endblock %}

practice/templates/practice/post_detail.html
{% extends "practice/layout.html" %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>{{ post.title }}</h2>

                {{ post.content|linebreaks }}

                <hr/>

                <h3>Series</h3>
                <ul>
                    {% for sequel in post.comment_set.all %}
                    <li>
                        {{ sequel.summary }}

                        <small> {{ sequel.content }}</small>
                        <small>created at {{ sequel.created_at }}</small>
                        <small>updated at {{ sequel.updated_at }}</small>
                    </li>
                    {% endfor %}
                </ul>

                <hr/>
                <a href="{% url "practice:relay_novel" %}" class="btn btn-primary">글 목록</a>
                <a href="{% url "practice:post_edit" post.id %}" class="btn btn-default">수정</a>
            </div>
        </div>
    </div>

{% endblock %}

practice/templates/practice/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

practice/templates/practice/radiostation.html
{% extends "practice/layout.html" %}

{% block content %}

<!--
<form action="" method="get">
    <input type="text" name="q" value="{{ q }}" />
    <input type="submit" value="검색" class="btn btn-primary" />
</form>   
-->
<div class="container">
    <div class ="row">
        <div class="col-sm-12">
            <div class="alert alert-info">         

            </div>

            

            <p>
                <form action = "" method="get">
                    <input type="text" name="q" value="{{ q }}" />
                    <input type="submit" value="검색" class="btn btn-primary"/>
                </form>
            </p>

            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>title</th>
                        <th>author</th>
                        <th>updated_at</th>
                        <th>공유</th>
                    </tr>
                </thead>
                <tbody>
                    {% for radiostation in radiostation_list %}
                    <tr>
                        <td>{{ RadioStation.id }}</td>
                        <td>{{ RadioStation.title }}</a></td>
                        <td><small>by {{ RadioStation.author }}</small></td>
                        <td><small>at {{ RadioStation.updated_at }}</small></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr/>
            <a href="{% url "practice:radio_station" %}" class="btn btn-primary">게시판 목록</a>
        </div>
    </div>
</div>

{% endblock %}

practice/templates/practice/relaynovel_list.html
{% extends "practice/layout.html" %}

{% block content %}

<!--
<form action="" method="get">
    <input type="text" name="q" value="{{ q }}" />
    <input type="submit" value="검색" class="btn btn-primary" />
</form>   
-->
<div class="container">
    <div class ="row">
        <div class="col-sm-12">
            <div class="alert alert-info">         

            </div>

            

            <p>
                <form action = "" method="get">
                    <input type="text" name="q" value="{{ q }}" />
                    <input type="submit" value="검색" class="btn btn-primary"/>
                </form>
            </p>

            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>title</th>
                        <th>updated_at</th>
                    </tr>
                </thead>
                <tbody>
                    {% for relay in relaynovel_list %}
                    <tr>
                        <td>{{ relay.id }}</td>
                        <td><a href="{% url "practice:post_detail" relay.id %}"> {{ relay.title }}</a></td>
                        <td><small>at {{ relay.updated_at }}</small></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr/>
            <a href="{% url "practice:relay_novel" %}" class="btn btn-primary">게시판 목록</a>
            <a href="{% url "practice:post_new" %}" class="btn btn-primary">새글쓰기</a>
        </div>
    </div>
</div>

{% endblock %}