hub/urls.py
# hub/urls.py

from django.conf.urls import url
from . import views


urlpatterns = [ 
    url(r'^$', views.list, name='hub_list'),
    url(r'^mynovel/$', views.mynovel, name='my_novel'),
    url(r'^sharednovel/$', views.sharednovel, name='shared_novel'),
    url(r'^mynovel/(?P<id>\d+)/$', views.post_detail, name='post_detail'),		
    url(r'^mynovel/new/$', views.post_new, name='post_new'),		
    url(r'^mynovel/(?P<id>\d+)/edit/$', views.post_edit, name = 'post_edit'),
    
]   

morakmorak/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.shortcuts import redirect


def root(request):
    return redirect('firstpage.html')


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')), #장고 기본 auth앱과 연동해서 사용하므로, namespace 적용하지 않음! 
    url(r'^accounts/', include('allauth.urls')), #include를 사용할 시에는 url에 $를 표시하면 안됨. $ 표시할 경우 패턴매칭 끝남.
    url(r'^hub/', include('hub.urls', namespace='hub')),
    url(r'^practice/', include('practice.urls', namespace='practice')),
   
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
   ]
#runserver 실행했을때, debug toolbar 활성화

hub/models.py
# hub/models.py
import re
from django import forms
from django.forms import ValidationError
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models

# Create your models here.

class MyNovel(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.CharField(max_length=100, blank=True)
    STATUS_CHOICES = (
        ('d', '작성중'),
        ('f', '작성완료'),
        ('p', '출판'),
    )
    
    status = models.Charfield(max_length=1, choices=STATUS_CHOICES)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('hub:post_detail', args=[self.id])



class Comment(models.Model):
    post = models.ForeignKey(MyNovel)
    author = models.Charfield(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    

hub/forms.py
from django import forms
from .models import MyNovel


Class PostForm(forms.Modelform):
    #dummy = forms.CharField(widget=NaverMapPointWidget(attrs={'width':"100%, 'height':200}))


    class Meta:
        model = MyNovel
        fields = '__all__'
        

hub/views.py
# hub/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from .models import MyNovel
from django.http import Http404
from .forms import PostForm

# Create your views here.
def mynovel(request):
    my_novel = MyNovel.objects.all() 
    print(request.user)#접속한 사용자의 아이디를 알 수 있음 

    return render(request, 'hub/mynovel.html', {
        'novel_list': my_novel,
        })


def sharednovel(request):
    shared_novel = MyNovel.objects.all()
    return render(request, 'hub/sharednovel.html',{
        'novel_list': shared_novel,
        })


def list(request):
    return render(request, 'hub/hublist.html')


def post_detail(request, id:
    #try:
    #   post = Post.obejcts.get(id=id)
    #except Post.DoesNotExist: 
    #   raise Http404

    post = get_object_or_404(Mynovel, id=id)
    return render(request, 'hub/post_detail.html', {
        'post':post,
    })


def post_edit(request, id):
    post = get_object_or_404(Mynovel, id=id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, '포스팅을 수정하였습니다.')
            return redirect(post) #post.get_absolute_url() => post detail

    else:
        form PostForm(instance=post)
    return render(request, 'hub/post_form.html', {
        'form': form, 
    })


    

hub/templates/hub/hublist.html
{% extends "hub/layout.html" %}

{% block content %}
<div class="container">
    <div class ="row">
        <div class="col-sm-12">
            <div class="alert alert-info">
                <ul>
                    <li>모락모락 글쓰기 연습장 컨텐츠 리스트 입니다.</li>
                    <li>다양한 글쓰기 방식으로 실력을 상승시켜보세요.</li>
                    <li> <a href ="{% url "hub:my_novel" %}" >나만의 소설 쓰기</a> </li>
                    <li> <a href ="{% url "hub:shared_novel" %}" >공유된 소설 보기</a> </li>
                </ul>
            </div>
        </div>
    </div>
</div>



{% endblock %}

hub/templates/hub/layout.html
{% extends "layout.html" %}

{% block title %}모락모락 단편소설 글쓰기 허브{% endblock %}

hub/templates/hub/mynovel.html
{% extends "hub/layout.html" %}

{% block content %}

<!--
<form action="" method="get">
    <input type="text" name="q" value="{{ q }}" />
    <input type="submit" value="검색" class="btn btn-primary" />
</form>   
-->
<div class="container">
    <div class ="row">
        <div class="col-sm-12">
            <div class="alert alert-info">         

            </div>

            

            <p>
                <form action = "" method="get">
                    <input type="text" name="q" value="{{ q }}" />
                    <input type="submit" value="검색" class="btn btn-primary"/>
                </form>
            </p>

            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>title</th>
                        <th>author</th>
                        <th>updated_at</th>
                        <th>상태</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in novel_list %}
                    <tr>
                        <td>{{ post.id }}</td>
                        <td><a href="{% url "hub:post_detail" post.id %}">
                            {{ post.title }}
                        </a></td>

                        <td><small>by {{ post.author }}</small></td>
                        <td><small>at {{ post.updated_at }}</small></td>
                        <td><small>{% if post.status == 'd' %}작성중{% endif %}
                            {% if post.status == 'f' %}작성완료{% endif %}
                            {% if post.status == 'p' %}출판{% endif %}
                        </small></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr/>
            <a href="{% url "hub:hub_list" %}" class="btn btn-primary">게시판 목록</a>
            <a href="{% url "hub:post_new" %}" class="btn btn-default">새글 쓰기</a>
        </div>
    </div>
</div>

{% endblock %}

hub/templates/hub/post_detail.html
{% extends "hub/layout.html" %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>{{ post.title }}</h2>

                {{ post.content|linebreaks }}

                <hr/>

                <h3>Comments</h3>
                <ul>
                    {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.message }}
                        <small>by {{ comment.author }}</small>
                        <small>at {{ comment.updated_at }}</small>
                    </li>
                    {% endfor %}
                </ul>

                <hr/>
                <a href="{% url "hub:my_novel" %}" class="btn btn-primary">글 목록</a>
                <a href="{% url "hub:post_edit" post.id %}" class="btn btn-default">수정</a>
            </div>
        </div>
    </div>

{% endblock %}

hub/templates/hub/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

hub/templates/hub/sharednovel.html
{% extends "hub/layout.html" %}

{% block content %}

<!--
<form action="" method="get">
    <input type="text" name="q" value="{{ q }}" />
    <input type="submit" value="검색" class="btn btn-primary" />
</form>   
-->
<div class="container">
    <div class ="row">
        <div class="col-sm-12">
            <div class="alert alert-info">         

            </div>

            

            <p>
                <form action = "" method="get">
                    <input type="text" name="q" value="{{ q }}" />
                    <input type="submit" value="검색" class="btn btn-primary"/>
                </form>
            </p>

            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>title</th>
                        <th>author</th>
                        <th>updated_at</th>
                        <th>공유</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in novel_list %}
                    <tr>
                        {% if post.status == 'p' %}
                            <td>{{ post.id }}</td>
                            <td>
                                {{ post.title }}
                            </a></td>

                            <td><small>by {{ post.author }}</small></td>
                            <td><small>at {{ post.updated_at }}</small></td>
                            <td><small>{% if post.status == 'd' %}작성중{% endif %}
                                {% if post.status == 'f' %}작성완료{% endif %}
                                {% if post.status == 'p' %}출판 {% endif %}
                            </small></td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            <hr/>
            <a href="{% url "hub:hub_list" %}" class="btn btn-primary">게시판 목록</a>
        </div>
    </div>
</div>

{% endblock %}